version: "3.5"
volumes:
  postgres_data: {}
  project_data: {}
services:
  postgresql:
    image: postgresql.subindexer-gnosis.public.dappnode.eth:0.1.0
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5440:5432"
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U postgres
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    labels:
      dappnode.dnp.upstreamImage: postgresql.subindexer-gnosis.public.dappnode.eth:0.1.0
  indexer:
    build:
      context: rindexer
      dockerfile: Dockerfile
    depends_on:
      postgresql:
        condition: service_healthy
    volumes:
      - project_data:/app/project_path
    working_dir: /app/project_path
    command:
      - start
      - indexer
    environment:
      DATABASE_URL: postgres://postgres:rindexer@postgresql:5432/postgres
    image: indexer.subindexer-gnosis.public.dappnode.eth:0.1.0
  api:
    build:
      context: api
      dockerfile: Dockerfile
    depends_on:
      postgresql:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://postgres:rindexer@postgresql:5432/postgres
      REDEEMER_PK: ${REDEEMER_PK}
      API_PORT: ${API_PORT:-3000}
      REDEEM_INTERVAL: ${REDEEM_INTERVAL:-3600}
      GNOSIS_RPC_URL: ${GNOSIS_RPC_URL:-https://rpc.gnosischain.com/}
    ports:
      - ${API_PORT:-3000}:${API_PORT:-3000}
    restart: unless-stopped
    image: api.subindexer-gnosis.public.dappnode.eth:0.1.0
